events/urls.py
from django.conf.urls import url

from . import views

urlpatterns = (
    url(r'^$', views.EventListView.as_view(), name='list'),

    url(r'^create/$', views.EventCreateView.as_view(),
        name='create'),

    url(r'^(?P<slug>[-\w]+)/$', views.EventDetailView.as_view(),
        name='detail'),

    url(r'^(?P<slug>[-\w]+)/edit/$', views.EventUpdateView.as_view(),
        name='edit'),

    url(r'^(?P<slug>[-\w]+)/contacts/$', views.EventContactsView.as_view(),
        name='contacts'),

    url(r'^invitation/(?P<slug>\w+)/$',
        views.InvitationDetailView.as_view(), name='invitation'),

    url(r'^invitation/(?P<slug>\w+)/preview/$',
        views.InvitationPreviewView.as_view(), name='invitation_preview'),

    url(r'^invitation/(?P<slug>\w+)/edit/$',
        views.InvitationUpdateView.as_view(), name='invitation_edit'),

)

oglam/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.defaults import page_not_found
from django.views.generic.base import RedirectView

from website import views

i = lambda s, prefix=None: url(r'^{}/'.format(prefix or s),
                               include('{}.urls'.format(s),
                                       namespace=prefix or s))

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^program/$', views.ProgramView.as_view(), name='program'),
    url(r'^faq/$', views.FAQView.as_view(), name='faq'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^terms/$', views.TermsView.as_view(), name='terms'),
    # url(r'^$', views.CreateProjectView.as_view(), name='home'),
    # url(r'^blog/', include('blog.urls')),
    i("projects"),
    i("users"),
    i("student_applications", "sa"),
    i("surveys"),
    i("events"),


    url('^social/', include('social_django.urls', namespace='social')),

    url(r'^hadmin/', include(admin.site.urls)),

    url(r'^404/$', lambda r: page_not_found(r, ValueError("Testing 123"))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(
        url(r'^xyzzy/$', views.TeaserView.as_view()),
    )

events/models.py
import logging

import markdown
from django.conf import settings
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from users.models import generate_code
from utils.mail import send_html_mail

logger = logging.getLogger(__name__)


class Event(models.Model):
    title = models.CharField(_('title'), max_length=400)
    slug = models.SlugField(validators=[RegexValidator('^[-\w]+$')])
    is_active = models.BooleanField(_("active"), default=True)
    is_open = models.BooleanField(_("invitations open"), default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   related_name="events_created",
                                   limit_choices_to={'is_staff': True})
    starts_at = models.DateTimeField(_("starts at"))
    ends_at = models.DateTimeField(_("ends at"))
    registration_ends_at = models.DateTimeField(_("registartion ends at"),
                                                null=True, blank=True)
    location = models.CharField(_('location'), max_length=400, null=True)
    description = models.TextField(_('description'), null=True)
    description_html = models.TextField(null=True)

    class Meta:
        verbose_name = _('event')
        verbose_name_plural = _('events')
        ordering = (
            '-starts_at',
        )

    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.description_html = markdown.markdown(
            self.description) if self.description else None
        super().save(force_insert, force_update, using, update_fields)

    def get_absolute_url(self):
        return reverse("events:detail", args=(self.slug,))

    def is_open_for_registration(self, dt=None):

        if dt is None:
            dt = timezone.now()

        if self.registration_ends_at:
            if self.registration_ends_at < dt:
                return False
        else:
            if self.starts_at < dt:
                return False

        return True

    def invite_user(self, user, created_by=None, base_url=None):

        try:
            o = EventInvitation.objects.get(event=self, user=user)
            created = False
        except EventInvitation.DoesNotExist:
            o = EventInvitation.objects.create(event=self, user=user,
                                               created_by=created_by)
            o.send(base_url)
            created = True

        return o, created


class EventInvitationStatus(object):
    NEW = 1
    SENT = 2
    APPROVED = 3
    MAYBE = 4
    DECLINED = 5

    choices = (
        (NEW, _('New invitation')),
        (SENT, _('Invitation sent')),
        (APPROVED, _('Invitation approved')),
        (MAYBE, _('Invitation maybe')),
        (DECLINED, _('Invitation declined')),
    )

    selectable = {APPROVED, DECLINED, MAYBE}


class EventInvitationAttendance(object):
    ATTENDED = 1
    PARTIALLY_ATTENDED = 2
    DID_NOT_ATTEND = 3

    choices = (
        (ATTENDED, _('Attended')),
        (PARTIALLY_ATTENDED, _('Partially attended')),
        (DID_NOT_ATTEND, _('Did not attend')),
    )


class EventInvitation(models.Model):
    event = models.ForeignKey(Event, related_name="invitations")
    slug = models.SlugField(default=generate_code)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   related_name="event_invitations_created",
                                   null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name="invitations")
    status = models.IntegerField(_('Status'),
                                 choices=EventInvitationStatus.choices,
                                 default=EventInvitationStatus.NEW)
    note = models.TextField(_('Note'), null=True, blank=True)

    statuses = EventInvitationStatus

    attendance = models.IntegerField(_('Attendance'),
                                     choices=EventInvitationAttendance.choices,
                                     null=True, blank=True)

    class Meta:
        ordering = ['event', 'status', 'created_at']
        unique_together = (
            ('event', 'user'),
        )

    def get_absolute_url(self):
        return reverse("events:invitation", args=(self.slug,))

    def registration_allowed(self, dt=None):
        """ returns True if user is allowed to register or modify her
            registration """

        if self.event.is_open_for_registration(dt):
            # still allowed.
            return True

        if self.status == EventInvitationStatus.APPROVED:
            # approved users can always change their mind.
            return True

        return False

    def send(self, base_url=""):
        """ sends an email to user and updated the invitaiton status """
        assert self.status == EventInvitationStatus.NEW

        context = {'base_url': base_url, 'object': self}

        subject = "{}: {}".format(_("Invitation"), self.event.title)

        html_message = render_to_string("events/emails/invitation.html",
                                        context)

        logger.info("Sending invitation #%d for event #%d to user #%d at %s"
                    % (self.id, self.event.id, self.user.id, self.user.email))

        send_html_mail(subject, html_message, self.user.email)

        self.status = EventInvitationStatus.SENT
        self.save()

        return True

events/forms.py
from django import forms

from . import models


class EventForm(forms.ModelForm):
    class Meta:
        model = models.Event
        fields = (
            'title',
            'slug',
            'is_active',
            'is_open',
            'starts_at',
            'ends_at',
            'registration_ends_at',
            'location',
            'description',
        )


class EventInvitationForm(forms.ModelForm):
    class Meta:
        model = models.EventInvitation
        fields = (
            'status',
            'note',
            'attendance',
        )

events/views.py
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.core.mail import mail_managers
from django.db import transaction
from django.forms import ChoiceField
from django.http.response import HttpResponseBadRequest
from django.shortcuts import redirect
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView
from django.views.generic.list import ListView

from events import forms
from events.models import EventInvitation, EventInvitationStatus, Event, \
    EventInvitationAttendance
from student_applications.views import ApplicationBulkOpsMixin
from users.models import PersonalInfo
from utils.base_views import TeamOnlyMixin


class EventMixin(TeamOnlyMixin):
    model = Event
    form_class = forms.EventForm


class EventListView(EventMixin, ListView):
    page_title = _("Events")


class EventCreateView(EventMixin, CreateView):
    page_title = _("Create event")

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class EventUpdateView(EventMixin, UpdateView):
    page_title = _("Update event")


class EventDetailView(TeamOnlyMixin, ApplicationBulkOpsMixin, DetailView):
    model = Event

    @property
    def page_title(self):
        return "{} | {}".format(self.object, _("Events"))

    def get_context_data(self, **kwargs):
        d = super().get_context_data(**kwargs)
        d['event_status'] = ChoiceField(
            (('', "---"),) + EventInvitationStatus.choices,
            False).widget.render(
            'event_status', None)
        d['attendance'] = ChoiceField(
            (('', "---"),) + EventInvitationAttendance.choices,
            False).widget.render(
            'attendance', None)
        return d

    def post(self, request, *args, **kwargs):

        if not request.user.has_perms("student_applications.bulk_application"):
            raise PermissionDenied()

        # if request.POST.get('resend'):
        #     o = self.get_object()
        #     for uid in self.get_user_ids():
        #         a = o.answers.get(user_id=uid)
        #         a.send(self.get_base_url())
        #         messages.success(request, "{} {} <{}>".format(
        #             _("Resent survey to"),
        #             a.user,
        #             a.user.email,
        #         ))

        with transaction.atomic():
            if request.POST.get('event_status'):
                try:
                    code = int(request.POST.get('event_status'))
                except ValueError:
                    return HttpResponseBadRequest("bad invitation status code")
                o = self.get_object()
                for uid in self.get_user_ids():
                    i = o.invitations.get(user_id=uid)
                    if i.status != code:
                        i.status = code
                        messages.info(request, "{}: {}".format(
                            i.user,
                            i.get_status_display()
                        ))
                        i.save()

            if request.POST.get('attendance'):
                try:
                    code = int(request.POST.get('attendance'))
                except ValueError:
                    return HttpResponseBadRequest("bad attendance code")
                o = self.get_object()
                for uid in self.get_user_ids():
                    i = o.invitations.get(user_id=uid)
                    if i.attendance != code:
                        i.attendance = code
                        messages.info(request, "{}: {}".format(
                            i.user,
                            i.get_attendance_display()
                        ))
                        i.save()

            resp = super().post(request, *args, **kwargs)

        return resp


class EventContactsView(TeamOnlyMixin, DetailView):
    model = Event
    template_name = "events/event_contacts.html"

    def get_context_data(self, **kwargs):
        def f(invite):
            assert isinstance(invite, EventInvitation)
            declined = invite.status == EventInvitationStatus.DECLINED
            try:
                info = invite.user.personalinfo
                return (
                    declined, info.hebrew_first_name, info.hebrew_last_name)
            except PersonalInfo.DoesNotExist:
                return (declined, invite.user.email, "")

        d = super().get_context_data(**kwargs)
        qs = self.object.invitations.all()
        d['invites'] = sorted(qs, key=f)
        return d


class InvitationDetailView(DetailView):
    model = EventInvitation

    def post(self, request, *args, **kwargs):

        try:
            status = int(request.POST.get('status', '0'))
        except ValueError:
            status = 0
        if status not in EventInvitationStatus.selectable:
            return HttpResponseBadRequest("Bad status value")

        note = request.POST.get('note')

        o = self.get_object()

        if o.event.ends_at < timezone.now():
            messages.error(request, _("Event already finished."))

        else:
            if status != o.status or note != o.note:
                if o.registration_allowed():
                    o.status = status
                    o.note = note
                    o.save()
                    subject = u"%s: %s - %s" % (
                        o.user, o.get_status_display(), o.event)
                    url = self.request.build_absolute_uri(
                        o.event.get_absolute_url())
                    message = u"%s (%s): %s - %s\n%s\n\n%s" % (
                        o.user, o.user.email,
                        o.get_status_display(),
                        o.event,
                        o.note,
                        url,
                    )
                    mail_managers(subject, message)
                    messages.success(request, _('Thank you!'))
                else:
                    messages.error(request, _('Registration already closed.'))
            else:
                messages.success(request, _('Thank you!'))

        return redirect(o)


class InvitationPreviewView(TeamOnlyMixin, DetailView):
    model = EventInvitation
    template_name = "emails/invitation.html"


class InvitationUpdateView(TeamOnlyMixin, UpdateView):
    model = EventInvitation
    form_class = forms.EventInvitationForm

    def form_valid(self, form):
        d = super().form_valid(form)
        messages.success(self.request, _("Invitation updated successfully"))
        return d

    def get_success_url(self):
        if 'from' in self.request.POST:
            return self.request.POST['from']
        return self.get_object().user.get_absolute_url()

events/templates/events/event_contacts.html
{% load i18n humanize staticfiles hackita %}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet"
          href="{% static "vendor/bootstrap/css/bootstrap-rtl.css" %}">
    <link rel="stylesheet"
          href="{% static "vendor/font-awesome/css/font-awesome.css" %}">
</head>

<body dir="rtl">

<div class="container-fluid">

    <h2>
        {{ object.title }}
    </h2>

    <ul class="list-group">
        {% for i in invites %}
            {% with info=i.user.personalinfo %}

                <li class="list-group-item">
                    <div class="pull-right">
                        {{ i.get_status_display }}
                    </div>
                    {{ forloop.counter }}.
                    &nbsp;
                    <i class="fa fa-square-o"></i>
                    &nbsp;

                    {% if info %}
                        <b>
                            {{ info.hebrew_first_name }}
                            {{ info.hebrew_last_name }}
                        </b>
                        {% if info.main_phone %}
                            ({{ info.main_phone }})
                        {% endif %}
                    {% else %}
                        {{ i.user }}
                    {% endif %}

                    {% if i.note %}
                        <br/>
                        <div style="margin: 0 20px">
                            {{ i.note|linebreaksbr }}
                        </div>
                    {% endif %}

                </li>

            {% endwith %}
        {% endfor %}
    </ul>

</div>

</body>
</html>

events/templates/events/event_detail.html
{% extends 'student_applications/bulk_base.html' %}
{% load i18n humanize staticfiles sa %}

{% block main_content %}

    <h1>
        <div class="pull-right">
            <a href="{% url "events:contacts" object.slug %}">
                <i class="fa fa-print"></i>
            </a>
            <a href="{% url "events:edit" object.slug %}"
               class="btn btn-primary">
                <i class="fa fa-pencil"></i>
            </a>
        </div>
        {{ object.title }}
    </h1>

    <div class="row">
        <div class="col-md-4">

            <ul class="list-group">
                <li class="list-group-item">
                    {% trans "at" %}: {{ object.location }}
                </li>
                <li class="list-group-item">
                    {% trans "From" %}: {{ object.starts_at|date:"d/n/Y H:i" }}
                </li>
                <li class="list-group-item">
                    {% trans "To" %}: {{ object.ends_at|date:"d/n/Y H:i" }}
                </li>
                {% if object.registration_ends_at %}
                    <li class="list-group-item">
                        {% trans "Registartion ends at" %}:
                        {{ object.registration_ends_at|date:"d/n/Y H:i" }}
                    </li>
                {% endif %}
            </ul>

            {% regroup object.invitations.all by get_status_display as groups %}

            {% for group in groups %}
                <div class="group">

                    <h2 class="grouper clickable">
                        {{ group.grouper }}
                    </h2>

                    <ul class="list-group">
                        {% for i in group.list %}
                            <li class="list-group-item">
                                <span class="badge">{{ forloop.counter }}</span>

                                <div class="pull-right">
                                    <a class="btn btn-default btn-xs"
                                       href="{% url "events:invitation_edit" i.slug %}?from={{ request.get_full_path }}"><i
                                            class="fa fa-pencil"
                                            title="{% trans "Edit" %}"></i></a>
                                    &nbsp;
                                </div>

                                <input class="user-email" type="checkbox"
                                       name="users"
                                       value="{{ i.user.id }}"
                                       data-email="{{ i.user.email }}"
                                        {% if i.status == i.statuses.APPROVED %}
                                       checked="1"{% endif %}/>
                                <a href="{{ i.user.get_absolute_url }}"
                                   title="{{ i.created_at }}">{{ i.user }}</a>
                                {% if i.attendance %}
                                    ({{ i.get_attendance_display }})
                                {% endif %}
                                {% if i.user.application %}
                                    {% app_status i.user.application %}
                                {% endif %}

                                {% if i.note %}
                                    <br/>
                                    <br/>
                                    <div class="panel panel-default">
                                        <div class="panel-body">
                                            <p>{{ i.note|linebreaksbr }}</p>
                                        </div>
                                    </div>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}

            <div>
                 <textarea id="emails" dir="ltr"
                           style="text-align: left; width:100%">
                 </textarea>
            </div>

        </div>

        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-body">
                    {{ object.description_html|safe }}
                </div>
            </div>
        </div>

    </div>


{% endblock %}

{% block custom_bulk_ops %}
    <div class="form-group">
        <label class="col-sm-4 control-label">{% trans "Invitation Status" %}</label>

        <div class="col-sm-8">
            {{ event_status }}
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-4 control-label">{% trans "Attendance" %}</label>

        <div class="col-sm-8">
            {{ attendance }}
        </div>
    </div>
{% endblock %}

{% block page_scripts %}

    <script src="{% static "js/event_detail.js" %}"></script>

{% endblock %}

events/templates/events/event_form.html
{% extends 'users/base.html' %}
{% load i18n bootstrap3 staticfiles %}

{% block extra_css %}
    <link rel="stylesheet"
          href="{% static "vendor/bootstrap-datetimepicker.css" %}"/>
{% endblock %}

{% block content %}

    <div class="register">

        <div class="panel panel-default">

            <div class="panel-heading">
                <h1>
                    {% if object.id %}
                        {% trans "Edit event" %}
                    {% else %}
                        {% trans "Create new event" %}
                    {% endif %}
                </h1>
            </div>

            <div class="panel-body">

                {% if form.form_description %}
                    {{ form.form_description|linebreaks }}
                {% endif %}

                <form method="post" novalidate>
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="form-actions">
                        <input class="btn btn-primary btn-lg" type="submit"
                               value="{% trans "Save" %}"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    <script src="{% static "vendor/moment.js" %}"></script>
    <script src="{% static "vendor/bootstrap-datetimepicker.js" %}"></script>
    <script src="{% static "vendor/bootstrap-datetimepicker.he.js" %}"></script>
    <script src="{% static "vendor/showdown.js" %}"></script>
    <script>
        $(function () {

            $("#id_starts_at,#id_ends_at,#id_registration_ends_at").datetimepicker({
                language: 'he',
                autoclose: true
            });
            var converter = new showdown.Converter();
            $('textarea').each(function () {
                var el = $(this);
                var preview = $('<div/>');
                el.after(preview);
                var refresh_preview = function () {
                    preview.html(converter.makeHtml(el.val()));
                };
                el.on('input', refresh_preview);
                refresh_preview();
            });
        });
    </script>
{% endblock %}

events/templates/events/event_list.html
{% extends 'users/base.html' %}
{% load i18n %}
{% load humanize %}

{% block content %}

    <div class="pull-right">
        <a href="{% url "events:create" %}" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i></a>
    </div>

    <h1>
        {{ view.page_title }}
    </h1>

    <ul class="list-group">
        {% for e in object_list %}
            <li class="list-group-item">
                <a href="{{ e.get_absolute_url }}">{{ e.title }}</a>
                - {{ e.starts_at|date:"d/n/Y H:i" }}
                ({{ e.invitations.count }})
            </li>
        {% endfor %}
    </ul>



{% endblock %}

events/templates/events/eventinvitation_detail.html
{% extends 'users/base.html' %}
{% load i18n %}
{% load humanize %}

{% block content %}

    <div class="row">
        <div class="col-lg-4">

            <ul class="list-group">
                <li class="list-group-item">
                    {% trans "to" context "invitation" %}: {{ object.user }}
                    ({{ object.user.email }})
                </li>
                <li class="list-group-item">
                    <b>{% trans "You are invited to" %} {{ object.event.title }}</b>
                </li>

                <li class="list-group-item">
                    {% trans "at" %} {{ object.event.location }}
                </li>
                <li class="list-group-item">
                    {% trans "From" %}: {{ object.event.starts_at|date:"d/n/Y H:i" }}
                </li>
                <li class="list-group-item">
                    {% trans "To" %}: {{ object.event.ends_at|date:"d/n/Y H:i" }}
                </li>
            </ul>

            <form method="post">
                {% csrf_token %}
                <h4>
                    {% trans "Will you attend the event?" %}
                </h4>

                {% if object.status == object.statuses.APPROVED or object.status == object.statuses.DECLINED or object.status == object.statuses.MAYBE %}
                    <div class="panel panel-default">
                        <div class="panel-body">
                            {% trans "Your current answer" %}:<b>
                            {% if object.status == object.statuses.APPROVED %}
                                {% trans "Yes" %}{% endif %}
                            {% if object.status == object.statuses.MAYBE %}
                                {% trans "Maybe" %}{% endif %}
                            {% if object.status == object.statuses.DECLINED %}
                                {% trans "No" %}{% endif %}
                        </b>
                            {% if object.note %}
                                <br/>
                                {% trans "Note" %}:<br/>
                                {{ object.note|linebreaksbr }}
                            {% endif %}
                        </div>
                    </div>
                {% endif %}

                {% if object.registration_allowed %}

                    {% if object.event.registration_ends_at %}
                        <p>
                            {% trans "Registartion ends at" %}:
                            {{ object.event.registration_ends_at|date:"d/n/Y H:i" }}
                        </p>
                    {% endif %}
                    <div class="form-group">
                        <label for="id_note">{% trans "Note" %}</label>
                    <textarea class="form-control" id="id_note"
                              name="note">{{ object.note|default:'' }}</textarea>
                    </div>
                    <div class="form-group">

                        <button name="status" class="btn btn-primary btn-lg"
                                value="{{ object.statuses.APPROVED }}">{% trans "Yes" %}</button>
                        <button name="status" class="btn btn-warning btn-lg"
                                value="{{ object.statuses.MAYBE }}">{% trans "Maybe" %}</button>
                        <button name="status" class="btn btn-danger btn-lg"
                                value="{{ object.statuses.DECLINED }}">{% trans "No" %}</button>
                    </div>

                {% else %}
                    <div class="alert-box">
                        {% trans "Registration already closed." %}
                    </div>
                {% endif %}

            </form>

        </div>
        <div class="col-lg-8">
            <div class="panel">
                {{ object.event.description_html|safe }}
            </div>
        </div>
    </div>
    </div>

{% endblock %}

events/templates/events/eventinvitation_form.html
{% extends 'users/base.html' %}
{% load i18n hackita bootstrap3 %}

{% block content %}

    <h1>
        {{ object.event|u }}
        &gt;
        {{ object.user|u }}
    </h1>

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% if request.GET.from %}
            <input type="hidden" name="from" value="{{ request.GET.from }}"/>
        {% endif %}

        <div class="form-group">
            <button class="btn btn-primary">{% trans "Save" %}</button>
        </div>

    </form>

{% endblock %}