oglam/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.defaults import page_not_found
from django.views.generic.base import RedirectView

from website import views

i = lambda s, prefix=None: url(r'^{}/'.format(prefix or s),
                               include('{}.urls'.format(s),
                                       namespace=prefix or s))

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^program/$', views.ProgramView.as_view(), name='program'),
    url(r'^faq/$', views.FAQView.as_view(), name='faq'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^terms/$', views.TermsView.as_view(), name='terms'),
    # url(r'^$', views.CreateProjectView.as_view(), name='home'),
    # url(r'^blog/', include('blog.urls')),
    i("projects"),
    i("users"),
    i("student_applications", "sa"),
    i("surveys"),
    i("events"),


    url('^social/', include('social_django.urls', namespace='social')),

    url(r'^hadmin/', include(admin.site.urls)),

    url(r'^404/$', lambda r: page_not_found(r, ValueError("Testing 123"))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(
        url(r'^xyzzy/$', views.TeaserView.as_view()),
    )

users/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^signup/$', views.SignupView.as_view(), name='signup'),
    url(r'^set-password/$', views.SetPasswordView.as_view(),
        name='set_password'),
    url(r'^set-names/$', views.UserDisplayNamesView.as_view(),
        name='set_names'),
    url(r'^check-your-email/$', views.ValidationSentView.as_view(),
        name='validation_sent'),
    url(r'^validate/(?P<code>\w{32})/$', views.ValidateView.as_view(),
        name='validate'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),

    url(r'^$', views.UserListView.as_view(), name='list'),

    url(r'^community/$', views.CommunityListView.as_view(),
        name='community'),
    url(r'^community/(?P<pk>\d+)/$', views.CommunityDetailView.as_view(),
        name='community_user'),
    url(r'^community-profile/$', views.UserCommunityDetailsUpdateView.as_view(),
        name='community_profile'),

    url(r'^(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/contact\.vcf$', views.UserVCFView.as_view(), name='vcf'),
    url(r'^(?P<pk>\d+)/tags/$', views.UserTagsEditView.as_view(), name='tags'),

    url(r'^all-emails/$', views.AllEmailsView.as_view(), name='list_emails'),

    url(r'^notes/$', views.UserNoteListView.as_view(), name='list_notes'),
    url(r'^notes/open/$', views.OpenUserNoteListView.as_view(),
        name='list_notes_open'),

    url(r'^notes/(?P<pk>\d+)/close/$', views.UserNoteCloseView.as_view(),
        name='close_note'),

    # url(r'^$', views.UserListView.as_view(),
    #     name='users'),
    #
    # url(r'^(?P<pk>\d+)/$', views.UserDetailView.as_view(), name='user'),

]

events/models.py
import logging

import markdown
from django.conf import settings
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from users.models import generate_code
from utils.mail import send_html_mail

logger = logging.getLogger(__name__)


class Event(models.Model):
    title = models.CharField(_('title'), max_length=400)
    slug = models.SlugField(validators=[RegexValidator('^[-\w]+$')])
    is_active = models.BooleanField(_("active"), default=True)
    is_open = models.BooleanField(_("invitations open"), default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   related_name="events_created",
                                   limit_choices_to={'is_staff': True})
    starts_at = models.DateTimeField(_("starts at"))
    ends_at = models.DateTimeField(_("ends at"))
    registration_ends_at = models.DateTimeField(_("registartion ends at"),
                                                null=True, blank=True)
    location = models.CharField(_('location'), max_length=400, null=True)
    description = models.TextField(_('description'), null=True)
    description_html = models.TextField(null=True)

    class Meta:
        verbose_name = _('event')
        verbose_name_plural = _('events')
        ordering = (
            '-starts_at',
        )

    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.description_html = markdown.markdown(
            self.description) if self.description else None
        super().save(force_insert, force_update, using, update_fields)

    def get_absolute_url(self):
        return reverse("events:detail", args=(self.slug,))

    def is_open_for_registration(self, dt=None):

        if dt is None:
            dt = timezone.now()

        if self.registration_ends_at:
            if self.registration_ends_at < dt:
                return False
        else:
            if self.starts_at < dt:
                return False

        return True

    def invite_user(self, user, created_by=None, base_url=None):

        try:
            o = EventInvitation.objects.get(event=self, user=user)
            created = False
        except EventInvitation.DoesNotExist:
            o = EventInvitation.objects.create(event=self, user=user,
                                               created_by=created_by)
            o.send(base_url)
            created = True

        return o, created


class EventInvitationStatus(object):
    NEW = 1
    SENT = 2
    APPROVED = 3
    MAYBE = 4
    DECLINED = 5

    choices = (
        (NEW, _('New invitation')),
        (SENT, _('Invitation sent')),
        (APPROVED, _('Invitation approved')),
        (MAYBE, _('Invitation maybe')),
        (DECLINED, _('Invitation declined')),
    )

    selectable = {APPROVED, DECLINED, MAYBE}


class EventInvitationAttendance(object):
    ATTENDED = 1
    PARTIALLY_ATTENDED = 2
    DID_NOT_ATTEND = 3

    choices = (
        (ATTENDED, _('Attended')),
        (PARTIALLY_ATTENDED, _('Partially attended')),
        (DID_NOT_ATTEND, _('Did not attend')),
    )


class EventInvitation(models.Model):
    event = models.ForeignKey(Event, related_name="invitations")
    slug = models.SlugField(default=generate_code)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                   related_name="event_invitations_created",
                                   null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name="invitations")
    status = models.IntegerField(_('Status'),
                                 choices=EventInvitationStatus.choices,
                                 default=EventInvitationStatus.NEW)
    note = models.TextField(_('Note'), null=True, blank=True)

    statuses = EventInvitationStatus

    attendance = models.IntegerField(_('Attendance'),
                                     choices=EventInvitationAttendance.choices,
                                     null=True, blank=True)

    class Meta:
        ordering = ['event', 'status', 'created_at']
        unique_together = (
            ('event', 'user'),
        )

    def get_absolute_url(self):
        return reverse("events:invitation", args=(self.slug,))

    def registration_allowed(self, dt=None):
        """ returns True if user is allowed to register or modify her
            registration """

        if self.event.is_open_for_registration(dt):
            # still allowed.
            return True

        if self.status == EventInvitationStatus.APPROVED:
            # approved users can always change their mind.
            return True

        return False

    def send(self, base_url=""):
        """ sends an email to user and updated the invitaiton status """
        assert self.status == EventInvitationStatus.NEW

        context = {'base_url': base_url, 'object': self}

        subject = "{}: {}".format(_("Invitation"), self.event.title)

        html_message = render_to_string("events/emails/invitation.html",
                                        context)

        logger.info("Sending invitation #%d for event #%d to user #%d at %s"
                    % (self.id, self.event.id, self.user.id, self.user.email))

        send_html_mail(subject, html_message, self.user.email)

        self.status = EventInvitationStatus.SENT
        self.save()

        return True

projects/models.py
import markdown
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _


class ProjectQuerySet(models.QuerySet):
    def random(self):
        return self.order_by('?')

    def by_title(self):
        return self.order_by('title')

    def published(self):
        return self.filter(is_published=True)

    def unpublished(self):
        return self.filter(is_published=False)

    def with_votes(self, user):
        for proj in self:
            proj.vote = proj.votes.filter(user=user).first()
        return self


class Project(models.Model):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(_('is published'), default=False)
    title = models.CharField(_('title'), max_length=250, blank=False)
    slug = models.CharField(_('slug'), max_length=100, null=True, unique=True)
    summary_markdown = models.TextField(_('summary (markdown)'))
    summary_html = models.TextField(_('summary (html)'), editable=False)
    link = models.URLField(_('link'), null=True, blank=True)
    picture = models.ImageField(upload_to='projects/', null=True, blank=True)

    objects = ProjectQuerySet.as_manager()

    class Meta:
        ordering = ['-created_at']
        verbose_name = _("project")
        verbose_name_plural = _("projects")

    def __str__(self):
        return self.title

    def natural_key(self):
        return (self.slug,)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.summary_html = markdown.markdown(self.summary_markdown)
        super().save(force_insert, force_update, using, update_fields)

    def get_absolute_url(self):
        return reverse("projects:detail", args=(self.slug,))

    def get_update_url(self):
        return reverse("projects:update", args=(self.id,))


class ProjectVoteQuerySet(models.QuerySet):
    def desc(self):
        return self.order_by('-score')

    def accepted_users(self):
        from student_applications.models import Application
        return self.filter(
            user__application__status__in=Application.Status.passed_interview,
        )

    def interested(self):
        return self.filter(score__gte=ProjectVote.Score.INTERESTED)


class ProjectVote(models.Model):
    class Score:
        UNINTERESTED = -1
        NEUTRAL = 0
        INTERESTED = 1
        VERY_INTERESTED = 2

        choices = (
            (UNINTERESTED, _('uninterested')),
            (NEUTRAL, _('neutral')),
            (INTERESTED, _('interested')),
            (VERY_INTERESTED, _('very interested')),
        )
        labels = dict((
            (UNINTERESTED, 'warning'),
            (NEUTRAL, 'default'),
            (INTERESTED, 'primary'),
            (VERY_INTERESTED, 'success'),
        ))

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='project_votes')
    project = models.ForeignKey(Project, related_name='votes')
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    score = models.IntegerField(choices=Score.choices)

    objects = ProjectVoteQuerySet.as_manager()

    class Meta:
        ordering = ['-created_at']
        unique_together = (
            ('user', 'project'),
        )

    def __str__(self):
        return "{} - {}: {}".format(
            self.user,
            self.project,
            self.get_score_display(),
        )

    def get_score_label(self):
        return self.Score.labels[self.score]


class ProjectCommentQuerySet(models.QuerySet):
    def asc(self):
        return self.order_by('created_at')

    def desc(self):
        return self.order_by('-created_at')


class ProjectComment(models.Model):
    class Scope:
        PUBLIC = 1
        PRIVATE = 2
        choices = (
            (PUBLIC, _("public")),
            (PRIVATE, _("private")),
        )

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='project_comments')
    project = models.ForeignKey(Project, related_name='comments')
    in_reply_to = models.ForeignKey('self', null=True, blank=True)
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    scope = models.IntegerField(_('comment view scope'), choices=Scope.choices)
    content = models.TextField(_("content"), blank=False)

    is_published = models.BooleanField(_("is published"), default=True)
    is_reviewed = models.BooleanField(_("is reviewed"), default=False)
    reviewed_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True,
                                    blank=True,
                                    related_name="project_comments_reviewed")
    reviewed_at = models.DateTimeField(_("reviewed at"), null=True, blank=True)

    objects = ProjectCommentQuerySet.as_manager()

    class Meta:
        ordering = ['-created_at']
        verbose_name = _("project comment")
        verbose_name_plural = _("project comments")

    def __str__(self):
        return "[#{}] {} - {}: {}".format(
            self.id,
            self.user,
            self.project,
            self.content,
        )

    def is_visible_to(self, user):
        if user.is_authenticated() and user.team_member:
            return True
        if not self.is_published:
            return False
        if self.scope == self.Scope.PUBLIC:
            return True
        return self.user == user

    def get_absolute_url(self):
        return "{}#comment-{}".format(
            self.project.get_absolute_url(),
            self.id,
        )


class ProjectBid(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='project_bids')
    project = models.ForeignKey(Project, related_name='bids')
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("updated at"), auto_now=True)
    value = models.IntegerField()

    class Meta:
        unique_together = (
            ('user', 'project'),
        )
        ordering = ['-created_at']
        verbose_name = _("project bid")
        verbose_name_plural = _("project bids")

    def __str__(self):
        return "{} - {}: {}".format(
            self.project,
            self.user,
            self.value,
        )

users/templates/users/_messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

users/templates/users/_user_note.html
{% load i18n humanize hackita projects %}


<li class="list-group-item{% if not note.visible_to_user %} list-group-item-warning{% endif %}"
    id="note-{{ note.id }}">
    <div class="list-group-item-heading">

        {% if user.team_member %}

            {% if note.is_open or note.closed_by %}
                <div class="pull-right">
                    <span class="label label-info">
                        {% if note.is_open %}
                            <i class="fa fa-exclamation"></i>
                            {% trans "Open" %}
                        {% else %}
                            {% if note.closed_by %}
                                {% trans "Closed by" %}
                                {{ note.closed_by }},
                                {{ note.closed_at|naturaltime }}
                            {% endif %}
                        {% endif %}
                    </span>
                    {% if note.is_open %}
                        <span class="clickable close"
                              data-url="{% url "users:close_note" note.id %}"
                              title="{% trans "Close" %}">
                            <i class="fa fa-close"></i>
                            
                        </span>
                    {% endif %}
                </div>
            {% endif %}
            {% if not note.visible_to_user %}
                <div class="pull-right">
                    <span class="label label-warning">
                        <i class="fa fa-user-secret"></i>
                        {% trans "Private" %}
                    </span>
                </div>
            {% endif %}
        {% endif %}
        {% if note.user == note.author %}
            <i class="fa fa-user"></i>
        {% else %}
            <i class="fa fa-users text-warning"></i>
        {% endif %}
        {% if show_user %}
            <b>
                {{ note.user|u }},
            </b>
            {% trans "By" %}
        {% endif %}
        {{ note.author|u }},
        <span title="{{ note.created_at }}">{{ note.created_at|naturaltime }}</span>:


    </div>
    <div class="list-group-item-body">
        {{ note.content|urlize|linebreaksbr }}
    </div>
</li>

users/templates/users/_user_tags.html
{% load i18n %}

{% for ut in u.tags.all %}
    <span class="label label-default utag" data-tag="{{ ut.tag.id }}">
        <i class="fa fa-tag"></i>
        {{ ut.tag }}
    </span>
    &nbsp;
{% endfor %}

{% if edit %}
    <a class="btn btn-default btn-xs"
       href="{% url "users:tags" u.id %}" title="{% trans "Edit Tags" %}">
        <i class="fa fa-tags"></i>
    </a>
{% endif %}

users/templates/users/set-names.html
{% extends 'users/base.html' %}
{% load i18n staticfiles bootstrap3 %}
{% block content %}

    <div class="panel panel-primary">

        <div class="panel-heading">
            <h1 class="panel-title">{% trans "My Profile" %}</h1>
        </div>

        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}

                <div class="text-center">
                    <button class="btn btn-primary btn-block">{% trans "Save" %}</button>
                </div>
            </form>
        </div>

    </div>

{% endblock %}

users/templates/users/user_detail.html
{% extends 'users/base.html' %}
{% load i18n humanize hackita staticfiles bootstrap3 %}

{% block page_title %}
    {{ object }}
    |
    {% trans "Users" %}
    |
{% endblock %}

{% block content %}

    <ol class="breadcrumb">
        <li>
            <a href="{% url "users:list" %}">
                {% trans "Users" %}
            </a>
        </li>
    </ol>

    <h1>
        <div class="pull-right">
            <a href="mailto:{{ object.email }}">{{ object.email }}</a>
        </div>
        {{ object|u }}
    </h1>

    {% with u=object %}
        {% if object.personalinfo %}
            {% include "users/_personal_info.html" %}
        {% endif %}
    {% endwith %}

    <div class="row">
        <div class="col-md-6">
            {% with app=object.application %}
                {% if app %}

                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title">
                                {% trans "Application Reviews" %}
                            </h3>
                        </div>

                        <ul class="list-group">
                            {% for review in app.reviews.all %}
                                <li class="list-group-item">
                                    {{ review.user|u }}
                                    <ul class="list-inline">
                                        {% for label, value in review.get_details %}
                                            <li>
                                                <b>{{ label }}:</b>
                                                {{ value }}
                                            </li>
                                        {% endfor %}
                                    </ul>
                                    {% if review.comments %}
                                        <blockquote>
                                            {{ review.comments|linebreaksbr }}
                                        </blockquote>
                                    {% endif %}
                                </li>
                            {% endfor %}
                            <li class="list-group-item">
                                <a class="btn btn-primary btn-block"
                                   href="{% url "sa:app_review" app.id %}">
                                    {% trans "Review" %}
                                </a>
                            </li>
                        </ul>
                    </div>

                {% endif %}
            {% endwith %}

            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <div class="pull-right">
                            <a class="btn btn-primary btn-xs"
                               data-toggle="collapse" href="#addnote">
                                <i class="fa fa-plus"></i>
                            </a>
                        </div>
                        {% trans "User Notes" %}
                    </h3>
                </div>

                <div id="addnote" class="panel-body collapse">
                    <div class="list-group-item-heading">
                        <b>{% trans "Add Note" %}</b>
                    </div>

                    <div class="list-group-item-body">
                        <form method="post" id="noteform">
                            {% csrf_token %}
                            {% bootstrap_form note_form %}
                            <button class="btn btn-primary"
                                    disabled="1">{% trans "Add" %}</button>
                            <div class="save">
                            <span class="loader collapse">
                                <i class="fa fa-spin fa-spinner"></i>
                            </span>
                            </div>
                            <div class="ok collapse text-success">
                                <i class="fa fa-check"></i>
                                {% trans "Saved sucessfully." %}
                            </div>
                        </form>
                    </div>
                </div>

                <ul class="list-group" id="notes">

                    {% for note in object.notes.all %}
                        {% include "users/_user_note.html" %}
                    {% endfor %}

                </ul>
            </div>
        </div>

        <div class="col-md-6">
            {% if object.invitations.count %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            {% trans "Events" %}
                        </h3>
                    </div>

                    <ul class="list-group">
                        {% for i in object.invitations.all %}
                            <li class="list-group-item">
                                <div class="pull-right">
                                    <a class="btn btn-default btn-xs"
                                       href="{% url "events:invitation_edit" i.slug %}?from={{ request.get_full_path }}"><i
                                            class="fa fa-pencil"
                                            title="{% trans "Edit" %}"></i></a>
                                    &nbsp;
                                </div>

                                {{ i.event|u }}
                                {{ i.get_status_display }}
                                {% if i.attendance %}
                                    ({{ i.get_attendance_display }})
                                {% endif %}

                                {% if i.note %}
                                    <br/>
                                    <br/>
                                    <div class="panel panel-default">
                                        <div class="panel-body">
                                            <p>{{ i.note|linebreaksbr }}</p>
                                        </div>
                                    </div>
                                {% endif %}
                            </li>

                        {% endfor %}
                    </ul>
                </div>


            {% endif %}

            {% if object.survey_answers.count %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            {% trans "Surveys" %}
                        </h3>
                    </div>

                    <ul class="list-group">
                        {% for a in object.survey_answers.all %}
                            <li class="list-group-item{% if not a.is_open %} list-group-item-warning{% endif %}">
                                <div class="list-group-item-heading">
                                    {% if not a.is_open %}
                                        <div class="pull-right">
                                            &nbsp;
                                            <i class="fa fa-check"></i>
                                        </div>
                                    {% endif %}
                                    {% if a.answered_at %}
                                        <a class="badge pull-right"
                                           data-toggle="collapse"
                                           href="#answer-{{ a.id }}"
                                           title="{{ a.answered_at }}">
                                            {{ a.answered_at|naturaltime }}

                                            <i class="fa fa-angle-down"></i>

                                        </a>
                                    {% endif %}

                                    {{ a.survey|u }}

                                    {% if a.answered_at %}
                                        {% with a.get_pretty as a %}
                                            {% for field in a.fields %}
                                                {% if field.html %}
                                                    <span class="label label-info key-{{ field.key }}"
                                                          title="{{ field.label }}"
                                                          data-key="{{ field.key }}"
                                                          data-value="{{ field.html }}"
                                                    >{{ field.html|truncatechars:20 }}</span>
                                                {% endif %}
                                            {% endfor %}
                                        {% endwith %}

                                    {% endif %}
                                </div>

                                {% if a.answered_at %}
                                    <div class="list-group-item-body">

                                        <div class="collapse"
                                             id="answer-{{ a.id }}">
                                            {% with a.get_pretty as a %}
                                                {% for field in a.fields %}
                                                    {% if field.html %}
                                                        <div class="user-answer">
                                                            <div class="user-answer-title">
                                                                {{ field.label }}
                                                            </div>
                                                            <div class="user-answer-content">
                                                                {{ field.html|urlize|linebreaksbr }}
                                                            </div>
                                                        </div>
                                                    {% endif %}
                                                {% endfor %}
                                            {% endwith %}
                                        </div>
                                    </div>
                                {% endif %}
                            </li>

                        {% endfor %}
                    </ul>
                </div>


            {% endif %}


            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        {% trans "Project Comments" %}
                    </h3>
                </div>

                <ul class="list-group" id="comments">
                    {% for c in object.project_comments.desc %}
                        {% include "projects/_project_comment.html" with show_project=True %}
                    {% endfor %}
                </ul>
            </div>
            {% if perms.projects.view_projectvote %}
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        {% trans "Project Votes" %}
                    </div>

                    {% regroup object.project_votes.desc by get_score_display as groups %}

                    <ul class="list-group">
                        {% for group in groups %}
                            <li class="list-group-item">
                                <b class="list-group-item-heading">
                                    {{ group.grouper }}
                                </b>

                                <div class="list-group-item-body">
                                    <ul class="list-unstyled">
                                        {% for item in group.list %}
                                            <li>
                                                {{ item.project|u }}
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>

    {% if object.application %}
        {% include "student_applications/_answers.html" with u=object accordion=True %}
    {% endif %}




{% endblock %}

{% block scripts %}
    <script src="{% static "js/csrf.js" %}"></script>
    <script src="{% static "vendor/jquery.form.js" %}"></script>
    <script src="{% static "js/user_detail.js" %}"></script>
{% endblock %}