oglam/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.defaults import page_not_found
from django.views.generic.base import RedirectView

from website import views

i = lambda s, prefix=None: url(r'^{}/'.format(prefix or s),
                               include('{}.urls'.format(s),
                                       namespace=prefix or s))

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^program/$', views.ProgramView.as_view(), name='program'),
    url(r'^faq/$', views.FAQView.as_view(), name='faq'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^terms/$', views.TermsView.as_view(), name='terms'),
    # url(r'^$', views.CreateProjectView.as_view(), name='home'),
    # url(r'^blog/', include('blog.urls')),
    i("projects"),
    i("users"),
    i("student_applications", "sa"),
    i("surveys"),
    i("events"),


    url('^social/', include('social_django.urls', namespace='social')),

    url(r'^hadmin/', include(admin.site.urls)),

    url(r'^404/$', lambda r: page_not_found(r, ValueError("Testing 123"))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns.append(
        url(r'^xyzzy/$', views.TeaserView.as_view()),
    )

projects/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.ProjectListView.as_view(), name='list'),
    url(r'^bid/$', views.ProjectBidView.as_view(), name='bid'),
    url(r'^bid/results/$', views.ProjectBidsView.as_view(), name='bid_results'),
    url(r'^show-votes/$', views.ProjectVotesView.as_view(), name='list_votes'),
    url(r'^create-new/$', views.ProjectCreateView.as_view(), name='create'),
    url(r'^(?P<slug>\w+)/$', views.ProjectDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/edit/$', views.ProjectUpdateView.as_view(),
        name='update'),
    url(r'^edit-comment/(?P<pk>\d+)/$',
        views.ProjectCommentUpdateView.as_view(),
        name='update_comment'),
    url(r'^review-comment/(?P<pk>\d+)/$',
        views.ProjectCommentMarkReviewedView.as_view(),
        name='review_comment'),

    url(r'^latest-comments/$', views.ProjectCommentListView.as_view(),
        name='list_comments'),

]

projects/models.py
import markdown
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _


class ProjectQuerySet(models.QuerySet):
    def random(self):
        return self.order_by('?')

    def by_title(self):
        return self.order_by('title')

    def published(self):
        return self.filter(is_published=True)

    def unpublished(self):
        return self.filter(is_published=False)

    def with_votes(self, user):
        for proj in self:
            proj.vote = proj.votes.filter(user=user).first()
        return self


class Project(models.Model):
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_at = models.DateTimeField(auto_now_add=True)
    is_published = models.BooleanField(_('is published'), default=False)
    title = models.CharField(_('title'), max_length=250, blank=False)
    slug = models.CharField(_('slug'), max_length=100, null=True, unique=True)
    summary_markdown = models.TextField(_('summary (markdown)'))
    summary_html = models.TextField(_('summary (html)'), editable=False)
    link = models.URLField(_('link'), null=True, blank=True)
    picture = models.ImageField(upload_to='projects/', null=True, blank=True)

    objects = ProjectQuerySet.as_manager()

    class Meta:
        ordering = ['-created_at']
        verbose_name = _("project")
        verbose_name_plural = _("projects")

    def __str__(self):
        return self.title

    def natural_key(self):
        return (self.slug,)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.summary_html = markdown.markdown(self.summary_markdown)
        super().save(force_insert, force_update, using, update_fields)

    def get_absolute_url(self):
        return reverse("projects:detail", args=(self.slug,))

    def get_update_url(self):
        return reverse("projects:update", args=(self.id,))


class ProjectVoteQuerySet(models.QuerySet):
    def desc(self):
        return self.order_by('-score')

    def accepted_users(self):
        from student_applications.models import Application
        return self.filter(
            user__application__status__in=Application.Status.passed_interview,
        )

    def interested(self):
        return self.filter(score__gte=ProjectVote.Score.INTERESTED)


class ProjectVote(models.Model):
    class Score:
        UNINTERESTED = -1
        NEUTRAL = 0
        INTERESTED = 1
        VERY_INTERESTED = 2

        choices = (
            (UNINTERESTED, _('uninterested')),
            (NEUTRAL, _('neutral')),
            (INTERESTED, _('interested')),
            (VERY_INTERESTED, _('very interested')),
        )
        labels = dict((
            (UNINTERESTED, 'warning'),
            (NEUTRAL, 'default'),
            (INTERESTED, 'primary'),
            (VERY_INTERESTED, 'success'),
        ))

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='project_votes')
    project = models.ForeignKey(Project, related_name='votes')
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    score = models.IntegerField(choices=Score.choices)

    objects = ProjectVoteQuerySet.as_manager()

    class Meta:
        ordering = ['-created_at']
        unique_together = (
            ('user', 'project'),
        )

    def __str__(self):
        return "{} - {}: {}".format(
            self.user,
            self.project,
            self.get_score_display(),
        )

    def get_score_label(self):
        return self.Score.labels[self.score]


class ProjectCommentQuerySet(models.QuerySet):
    def asc(self):
        return self.order_by('created_at')

    def desc(self):
        return self.order_by('-created_at')


class ProjectComment(models.Model):
    class Scope:
        PUBLIC = 1
        PRIVATE = 2
        choices = (
            (PUBLIC, _("public")),
            (PRIVATE, _("private")),
        )

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='project_comments')
    project = models.ForeignKey(Project, related_name='comments')
    in_reply_to = models.ForeignKey('self', null=True, blank=True)
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    scope = models.IntegerField(_('comment view scope'), choices=Scope.choices)
    content = models.TextField(_("content"), blank=False)

    is_published = models.BooleanField(_("is published"), default=True)
    is_reviewed = models.BooleanField(_("is reviewed"), default=False)
    reviewed_by = models.ForeignKey(settings.AUTH_USER_MODEL, null=True,
                                    blank=True,
                                    related_name="project_comments_reviewed")
    reviewed_at = models.DateTimeField(_("reviewed at"), null=True, blank=True)

    objects = ProjectCommentQuerySet.as_manager()

    class Meta:
        ordering = ['-created_at']
        verbose_name = _("project comment")
        verbose_name_plural = _("project comments")

    def __str__(self):
        return "[#{}] {} - {}: {}".format(
            self.id,
            self.user,
            self.project,
            self.content,
        )

    def is_visible_to(self, user):
        if user.is_authenticated() and user.team_member:
            return True
        if not self.is_published:
            return False
        if self.scope == self.Scope.PUBLIC:
            return True
        return self.user == user

    def get_absolute_url(self):
        return "{}#comment-{}".format(
            self.project.get_absolute_url(),
            self.id,
        )


class ProjectBid(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             related_name='project_bids')
    project = models.ForeignKey(Project, related_name='bids')
    created_at = models.DateTimeField(_("created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("updated at"), auto_now=True)
    value = models.IntegerField()

    class Meta:
        unique_together = (
            ('user', 'project'),
        )
        ordering = ['-created_at']
        verbose_name = _("project bid")
        verbose_name_plural = _("project bids")

    def __str__(self):
        return "{} - {}: {}".format(
            self.project,
            self.user,
            self.value,
        )

projects/views.py
import csv
import io
import json
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import mail_managers
from django.db import transaction
from django.db.models import Sum
from django.http import JsonResponse, HttpResponse
from django.http.response import HttpResponseBadRequest
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView, ListView, DetailView, UpdateView, \
    View
from django.views.generic.detail import SingleObjectMixin

from users.views import CommunityMixin
from utils.base_views import UIMixin, PermissionMixin, TeamOnlyMixin
from . import forms, models

logger = logging.getLogger(__name__)


class ProjectListView(UIMixin, ListView):
    name = 'projects'
    model = models.Project

    def get_context_data(self, **kwargs):
        d = super().get_context_data(**kwargs)
        published = self.get_queryset().published().random()
        if self.request.user.is_authenticated():
            for proj in published:
                proj.vote = proj.votes.filter(
                    user=self.request.user,
                ).first()
                proj.bid = proj.bids.filter(
                    user=self.request.user,
                ).first()
        d['published'] = published
        return d


class ProjectBidView(CommunityMixin, ProjectListView):
    TOTAL = 100
    template_name = "projects/project_bid.html"

    def post(self, request, *args, **kwargs):
        try:
            bid = json.loads(self.request.POST['bid'])
            bid = [(models.Project.objects.get(id=k), int(v)) for k, v in bid]
        except (ValueError, KeyError, models.Project.DoesNotExist):
            return HttpResponseBadRequest("bid not found")

        if not all(0 <= n <= self.TOTAL for p, n in bid):
            return HttpResponseBadRequest("bid item not in range")

        if sum(x[1] for x in bid) != self.TOTAL:
            return HttpResponseBadRequest("wrong total")

        with transaction.atomic():
            for p, v in bid:
                o, created = models.ProjectBid.objects.get_or_create(
                    project=p,
                    user=request.user,
                    defaults={'value': v}
                )
                if not created:
                    o.value = v
                    o.save()
            assert models.ProjectBid.objects.filter(user=request.user
                                                    ).aggregate(
                total=Sum('value'))['total'] == self.TOTAL
        messages.success(self.request, _("Thank you!"))
        subject = "{}: {}".format(_("New bid"), request.user.community_name)
        bids = sorted([x for x in bid if x[1]], key=lambda x: x[1],
                      reverse=True)
        html_message = render_to_string("projects/bid_email.html", {
            'base_url': self.request.build_absolute_uri('/')[:-1],
            'bid': bids,
        }, request=self.request)
        message = "\n".join(["{}: {}".format(p, v) for p, v in bids])
        mail_managers(subject, message, html_message=html_message)
        return redirect("projects:list")


class ProjectBidsView(TeamOnlyMixin, View):
    def get(self, request, *args, **kwargs):
        qs = models.ProjectBid.objects.order_by(
            'project__title',
            'user__community_name'
        )
        o = io.StringIO()
        w = csv.writer(o)
        w.writerow((_('project'), _('user'), _('bid')))
        for bid in qs:
            w.writerow((bid.project.title, bid.user.community_name, bid.value))
        o.seek(0)
        return HttpResponse(o, content_type="text/csv")


class ProjectVotesView(TeamOnlyMixin, UIMixin, ListView):
    template_name = "projects/project_list_votes.html"
    model = models.Project


class ProjectDetailView(UIMixin, DetailView):
    name = 'projects'
    model = models.Project

    def get_vote_form(self, data=None):
        if not self.request.user.is_authenticated():
            return None
        o = models.ProjectVote.objects.filter(
            project=self.object,
            user=self.request.user
        ).first()
        form = forms.ProjectVoteForm(data, instance=o)
        form.fields['score'].widget.choices = form.fields[
                                                  'score'].widget.choices[1:]
        return form

    def get_comment_form(self, data=None):
        return forms.ProjectCommentForm(data)

    def get_context_data(self, **kwargs):
        d = super().get_context_data(**kwargs)
        d['vote_form'] = self.get_vote_form()
        d['comment_form'] = self.get_comment_form()
        return d

    def handle_vote_form(self):
        form = self.get_vote_form(self.request.POST)
        if not form.is_valid():
            return False

        form.instance.user = self.request.user
        form.instance.project = self.object
        form.save()
        return True

    def handle_comment_form(self):
        form = self.get_comment_form(self.request.POST)
        if not form.is_valid():
            return False

        form.instance.user = self.request.user
        form.instance.project = self.object
        form.save()
        form.instance.new = True

        url = self.request.build_absolute_uri(form.instance.get_absolute_url())

        subject = "{}: {} -> {}".format(
            _("Comment posted"),
            self.request.user,
            self.object,
        )
        message = "{}\n\n{}\n{}\n\n{} ({})".format(
            url,
            form.instance.get_scope_display(),
            form.instance.content,
            self.request.user,
            self.request.user.email,
        )
        mail_managers(subject, message)

        response = render_to_string("projects/_project_comment.html",
                                    {'c': form.instance, },
                                    request=self.request)
        return response

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        form_type = self.request.POST.get('type')

        if form_type == 'vote':
            result = self.handle_vote_form()
        elif form_type == 'comment':
            result = self.handle_comment_form()
        else:
            result = False

        return JsonResponse({'result': result}, safe=False,
                            status=200 if result else 400)


class ProjectCreateView(PermissionMixin, UIMixin, CreateView):
    name = 'projects'
    permission_required = "projects.create_project"
    model = models.Project
    form_class = forms.ProjectForm

    # def get_success_url(self):
    #     return self.object.get_update_url()

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super(ProjectCreateView, self).form_valid(form)


class ProjectUpdateView(PermissionMixin, UIMixin, UpdateView):
    permission_required = "projects.change_project"
    model = models.Project
    form_class = forms.ProjectForm


class ProjectCommentListView(TeamOnlyMixin, UIMixin, ListView):
    model = models.ProjectComment
    paginate_by = 50


class ProjectCommentUpdateView(PermissionMixin, UIMixin, UpdateView):
    permission_required = "projects.projectcomment_change"
    model = models.ProjectComment
    form_class = forms.ProjectCommentEditForm


class ProjectCommentMarkReviewedView(PermissionMixin, SingleObjectMixin, View):
    permission_required = "projects.projectcomment_change"
    model = models.ProjectComment

    def post(self, request, *args, **kwargs):
        o = self.get_object()
        o.is_reviewed = True
        o.reviewed_by = self.request.user
        o.reviewed_at = timezone.now()
        o.save()
        return JsonResponse({})

projects/templates/projects/_project_comment.html
{% load i18n humanize hackita projects %}

{% if c|comment_is_visible:user %}

    <li class="list-group-item{% if c.new %} list-group-item-success{% elif not c.is_published %} list-group-item-danger{% elif c.scope == c.Scope.PRIVATE %} list-group-item-warning{% endif %}{% if c.new %} list-group-item-success{% endif %}{% if not c.is_published %} deleted{% endif %}"
        id="comment-{{ c.id }}">
        <div class="list-group-item-heading">
            {% if perms.projects.projectcomment_change %}
                <div class="pull-right">
                    <a class="btn btn-success btn-xs"
                       href="{% url "projects:update_comment" c.id %}"><i
                            class="fa fa-edit"></i></a>
                </div>
            {% endif %}
            {% if c.scope == c.Scope.PRIVATE %}
                <div class="pull-right">
                    <span class="label label-warning">
                        <i class="fa fa-user-secret"></i>
                        {% trans "Private" %}
                    </span>
                </div>
            {% endif %}
            {% if not c.is_published %}
                <div class="pull-right">
                    <span class="label label-danger">
                        <i class="fa fa-trash"></i> {% trans "Deleted" %}
                    </span>
                </div>
            {% endif %}
            {% if user.team_member %}
                <div class="pull-right">
                    <span class="label label-info" title="{% trans "Reviewed by" %}">
                        <i class="fa fa-binoculars"></i>
                        {% if c.is_reviewed %}
                            {{ c.reviewed_by }},
                            {{ c.reviewed_at|naturaltime }}
                        {% else %}
                            <span class="review"
                                  data-url="{% url "projects:review_comment" c.id %}">
                                {% trans "Unreviewed" %}
                            </span>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
            <b>
                {% if show_project %}
                    {{ c|u:'project' }}:<br/>
                {% endif %}
                {{ c.user }},
                {% if user.team_member %}
                    ({{ c.user|u:'email' }})
                {% endif %}
                <span title="{{ c.created_at }}">{{ c.created_at|naturaltime }}</span>:
            </b>
        </div>
        <div class="list-group-item-body">
            {{ c.content|linebreaksbr }}
        </div>
    </li>

{% endif %}

projects/templates/projects/bid_email.html
{% load i18n humanize hackita staticfiles %}
<div dir="rtl">
    <h1>
        {% trans "Bid for" %}
        <a href="

                {{ base_url }}{{ user.get_absolute_url }}">{{ user.community_name }}</a>
    </h1>

    <ul>
        {% for p, v in bid %}
            <li>
                {{ p }}: {{ v }}
            </li>
        {% endfor %}
    </ul>
</div>

projects/templates/projects/project_bid.html
{% extends 'users/base.html' %}
{% load i18n humanize hackita staticfiles %}

{% block content %}

    <h1>
        {% trans "Projects" %}
    </h1>

    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="bid" id="v">
        <ul class="list-group bid">
            <li class="list-group-item">
                <h3 class="text-right">
                    <span class="limit">100</span>
                    /
                    <span class="total">0</span>

                    <button class="btn btn-primary"
                            disabled="1">{% trans "Send" %}</button>
                </h3>
            </li>

            {% for object in published %}
                <li class="list-group-item">
                    <h4 class="list-group-item-heading">
                        <div class="row">
                            <div class="col-sm-6">
                                {{ object|u }}
                            </div>
                            <div class="col-sm-6">
                                <div class="bid-item row">
                                    <div class="col-xs-9">
                                        <input type="range" min="0" max="100"
                                               value="{{ object.bid.value|default:0 }}" data-id="{{ object.id }}">
                                    </div>
                                    <div class="col-xs-3">
                                        <input type="number" min="0" max="100"
                                               value="{{ object.bid.value|default:0 }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </h4>

                    <p class="list-group-item-text">
                        {{ object.summary }}
                    </p>
                </li>
            {% endfor %}

        </ul>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static "js/project_bid.js" %}"></script>
{% endblock %}

projects/templates/projects/project_form.html
{% extends 'users/base.html' %}
{% load i18n humanize hackita bootstrap3 %}

{% block content %}

    <ol class="breadcrumb">
        <li>
            <a href="{% url "projects:list" %}">
                {% trans "Projects" %}
            </a>
        </li>
    </ol>

    <div class="panel panel-primary">

        <div class="panel-heading">
            <h3 class="panel-title">
                {% if project %}
                    {% trans "Update Project" %}
                {% else %}
                    {% trans "Create Project" %}
                {% endif %}
            </h3>
        </div>

        <div class="panel-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button class="btn btn-primary">
                    {% if project %}
                        {% trans "Save" %}
                    {% else %}
                        {% trans "Create" %}
                    {% endif %}
                </button>
            </form>
        </div>

    </div>
    <div class="panel panel-default">

        <div class="panel-body">
            {% if project %}
                {{ object.content_html|safe }}
            {% endif %}
        </div>

    </div>



{% endblock %}

projects/templates/projects/project_list.html
{% extends 'users/base.html' %}
{% load i18n humanize hackita staticfiles %}

{% block content %}

    <div class="row">
        <div class="col-s-push-1 col-s-10 col-md-push-2 col-md-8">
            <h1>
                {% if user.team_member %}
                    <div class="pull-right">
                        <a href="{% url "projects:list_votes" %}">
                            <i class="fa fa-users"></i>
                        </a>
                    </div>
                {% endif %}

                {% trans "Projects" %}
            </h1>

            <ul class="list-group project-list">

                {% for object in published %}
                    <li class="list-group-item{% if object.vote %} list-group-item-warning{% endif %}">
                        <div class="row">
                            <div class="col-s-4">
                                <a href="{{ object.get_absolute_url }}">
                                    {% if object.picture %}
                                        <img class="img-responsive"
                                             src="{{ object.picture.url }}">
                                    {% else %}
                                        <img class="img-responsive"
                                             src="{% static "img/glam/icon-library.png" %}"/>
                                    {% endif %}
                                </a>
                            </div>
                            <div class="col-s-8">
                                {% if object.bid and object.bid.value %}
                                    <div class="pull-right label label-success">{{ object.bid.value }}
                                        <i class="fa fa-money"></i>
                                    </div>
                                {% endif %}
                                {% if object.vote %}

                                    <div class="label label-{{ object.vote.get_score_label }} pull-right">
                                        {{ object.vote.get_score_display }}
                                    </div>
                                {% endif %}
                                <h4 class="list-group-item-heading">
                                    {{ object|u }}
                                </h4>

                                <p class="list-group-item-text">
                                    {{ object.summary_html|safe | urlizetrunc:50 | linebreaksbr }}
                                </p>

                            </div>
                        </div>
                    </li>
                {% endfor %}

            </ul>

            {% if perms.projects.view_project %}

                <ul class="list-group">

                    {% for object in object_list.unpublished %}
                        <li class="list-group-item{% if object.vote %} list-group-item-warning{% endif %}">
                            <div class="row">
                                <div class="col-sm-4">
                                    <a href="{{ object.get_absolute_url }}">
                                        {% if object.picture %}
                                            <img class="img-responsive"
                                                 src="{{ object.picture.url }}">
                                        {% else %}
                                            <img class="img-responsive"
                                                 src="{% static "img/glam/icon-library.png" %}"/>
                                        {% endif %}
                                    </a>
                                </div>
                                <div class="col-sm-8">
                                    {% if object.bid and object.bid.value %}
                                        <div class="pull-right label label-success">{{ object.bid.value }}
                                            <i class="fa fa-money"></i>
                                        </div>
                                    {% endif %}
                                    {% if object.vote %}

                                        <div class="label label-{{ object.vote.get_score_label }} pull-right">
                                            {{ object.vote.get_score_display }}
                                        </div>
                                    {% endif %}
                                    <h4 class="list-group-item-heading">
                                        {{ object|u }}
                                    </h4>

                                    <p class="list-group-item-text">
                                        {{ object.summary_html|safe | urlizetrunc:50 | linebreaksbr }}
                                    </p>

                                </div>
                            </div>
                        </li>
                    {% endfor %}

                    <li class="list-group-item list-group-item-warning">
                        <a href="{% url "projects:create" %}">{% trans "Create Project" %}</a>
                    </li>

                </ul>
            {% endif %}

        </div>
    </div>

{% endblock %}

projects/templates/projects/project_list_votes.html
{% extends 'users/base.html' %}
{% load i18n humanize hackita staticfiles %}

{% block content %}

    <h1>
        {% trans "Projects" %}
    </h1>

    <div class="blocks">
        {% for object in object_list.by_title %}
            <div class="block">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="pull-right">
                            <i class="fa fa-arrows"></i>
                        </div>
                        {{ object|u }}
                    </div>

                    {% regroup object.votes.interested.accepted_users.desc by get_score_display as groups %}

                    <ul class="list-group">
                        {% for group in groups %}
                            <li class="list-group-item">
                                <b class="list-group-item-heading">
                                    {{ group.grouper }}
                                </b>

                                <div class="list-group-item-body">
                                    <ul class="list-inline">
                                        {% for item in group.list|shuffle %}
                                            <li class="user" data-id="{{ item.user.id }}">
                                                {{ item.user|u }}
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static "vendor/jquery-sortable.js" %}"></script>
    <script src="{% static "js/project_list_votes.js" %}"></script>
{% endblock %}

projects/templates/projects/projectcomment_form.html
{% extends 'users/base.html' %}
{% load i18n humanize hackita bootstrap3 %}

{% block content %}

    <ol class="breadcrumb">
        <li>
            <a href="{% url "projects:list" %}">
                {% trans "Projects" %}
            </a>
        </li>
        <li>
            {{ object.project|u }}
        </li>
    </ol>

    <div class="panel panel-primary">

        <div class="panel-heading">
            <h3 class="panel-title">
                {% trans "Edit Comment" %}
            </h3>
        </div>

        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button class="btn btn-primary">
                    {% trans "Save" %}
                </button>
            </form>
        </div>

    </div>



{% endblock %}